# Proyecto 1

In [135]:
# suma de listas es una lista más grande
x = [1,2,3]
y = [4,5,6]
x + y

[1, 2, 3, 4, 5, 6]

In [136]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
print(x)

[[1 2 3]
 [4 5 6]]


In [138]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [139]:
x[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [177]:
x.shape

(3,)

In [178]:
print(x)

[1 2 3]


In [179]:
print(np.transpose(x))

[1 2 3]


In [181]:
x.transpose().shape

(3,)

In [182]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [183]:
x.shape

(3, 1)

In [160]:
x.transpose()

array([[1, 2, 3]])

In [184]:
x.transpose().shape

(1, 3)

## Ejercicio 1

In [146]:
class Array:
    "Una clase minima para algebra lineal"    
    def __init__(self, list_of_rows): 
        "Constructor"
        self.data = list_of_rows
        self.shape = (len(list_of_rows), len(list_of_rows[0]))
    def __repr__(self):
        return str(self.data)
    def __str__(self):
        s = str()  # s = ""
        for r in range(self.shape[0]):
            #s = s + str(self.data[r]) + '\n'
            #s += f"{self.data[r]}\n"
            s += str(self.data[r]) + '\n'
        return s

In [147]:
A = Array([[1,2,3], [4,5,6]])
A.__dict__ # el campo escondido __dict__ permite acceder a las propiedades de clase de un objeto

{'data': [[1, 2, 3], [4, 5, 6]], 'shape': (2, 3)}

In [148]:
str(A.data)

'[[1, 2, 3], [4, 5, 6]]'

In [149]:
A.shape

(2, 3)

In [150]:
A.__repr__()

'[[1, 2, 3], [4, 5, 6]]'

In [151]:
A

[[1, 2, 3], [4, 5, 6]]

In [152]:
print(A)

[1, 2, 3]
[4, 5, 6]



In [153]:
A.__str__()

'[1, 2, 3]\n[4, 5, 6]\n'

## Validación e indexación

In [154]:
print(isinstance([1,2,3], list))
print(isinstance([[1,2,3],[4,5,6]], list))
print(isinstance([1,2,3][0], list))
print(isinstance([[1,2,3],[4,5,6]][0], list))

True
True
False
True


In [155]:
all([isinstance(x, list) for x in [[1,2,3],[4,5,6]]])

True

In [156]:
[isinstance(x, list) for x in [[1,2,3]]]

[True]

In [157]:
if False:
    print("True")
else:
    print("False")

False


In [161]:
[3 == len(x) for x in [[1,2,3],[4,5,6]]]

[True, True]

In [163]:
type(3.0)

float

In [198]:
class Array:
    "Una clase minima para algebra lineal"    
    def __init__(self, list_of_rows): 
        "Constructor"
        if not isinstance(list_of_rows, list):
            raise Exception("list_of_rows must be a list")
        if not all([isinstance(x, list) for x in list_of_rows]):
            raise Exception("list_of_rows must be a list of lists")
        len_row = min([len(x) for x in list_of_rows])
        if not all([len_row == len(x) for x in list_of_rows]):
            raise Exception("all rows in list_of_rows must be the same length")
        for row in list_of_rows:
            #if not all([type(x) == float for x in row]):
            if not all([isinstance(x, float) for x in row]):
                raise Exception("all entries in list_of_rows must be float")
        self.data = list_of_rows
        self.shape = (len(list_of_rows), len(list_of_rows[0]))
    def __repr__(self):
        return str(self.data)
    def __str__(self):
        s = str()  # s = ""
        for r in range(self.shape[0]):
            #s = s + str(self.data[r]) + '\n'
            #s += f"{self.data[r]}\n"
            s += str(self.data[r]) + '\n'
        return s
    def __getitem__(self, idx):
        if not len(idx) == 2: 
            raise Exception("idx must have a length of 2")
        return self.data[idx[0]][idx[1]]

In [199]:
Array([1,2,3])

Exception: list_of_rows must be a list of lists

In [200]:
Array([[1,2,3],[4,5,6]])

Exception: all entries in list_of_rows must be float

In [201]:
A = Array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
A

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [202]:
A = Array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
A[1,2,3]

Exception: array has two dimensions

In [203]:
A[1,2]

6.0

## Ejercicio 2

In [208]:
class Array:
    "Una clase minima para algebra lineal"    
    def __init__(self, list_of_rows): 
        "Constructor"
        if not isinstance(list_of_rows, list):
            raise Exception("list_of_rows must be a list")
        if not all([isinstance(x, list) for x in list_of_rows]):
            raise Exception("list_of_rows must be a list of lists")
        len_row = min([len(x) for x in list_of_rows])
        if not all([len_row == len(x) for x in list_of_rows]):
            raise Exception("all rows in list_of_rows must be the same length")
        for row in list_of_rows:
            #if not all([type(x) == float for x in row]):
            if not all([isinstance(x, float) for x in row]):
                raise Exception("all entries in list_of_rows must be float")
        self.data = list_of_rows
        self.shape = (len(list_of_rows), len(list_of_rows[0]))
    def __repr__(self):
        return str(self.data)
    def __str__(self):
        s = str()  # s = ""
        for r in range(self.shape[0]):
            #s = s + str(self.data[r]) + '\n'
            #s += f"{self.data[r]}\n"
            s += str(self.data[r]) + '\n'
        return s
    def __getitem__(self, idx):
        if not len(idx) == 2: 
            raise Exception("idx must have a length of 2")
        return self.data[idx[0]][idx[1]]
    def __setitem__(self, idx, new_value):
        if not len(idx) == 2: 
            raise Exception("idx must have a length of 2")
        if not isinstance(new_value, float): 
            raise Exception("new_value must be a float")
        self.data[idx[0]][idx[1]] = new_value

In [209]:
A = Array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
A

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [211]:
A[1,2] = 7.0
A

[[1.0, 2.0, 3.0], [4.0, 5.0, 7.0]]

## Ejercicio 3

In [224]:
def Zeros(idx):
    if not isinstance(idx, tuple):
        raise Exception("idx must be a tuple")
    return [[0 for i in range(idx[1])] for j in range(idx[0])]

In [225]:
Zeros((2,3))

[[0, 0, 0], [0, 0, 0]]